# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 09:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_text', models.CharField(max_length=255)),
                ('seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='HasSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Confirmed')], default=1),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='img',
            field=models.ImageField(blank=True, default='/static/musician/images/vm.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image_skill',
            field=models.ImageField(blank=True, default='/static/musician/images/question-mark-icon.png', null=True, upload_to='skill/'),
        ),
        migrations.AddField(
            model_name='post',
            name='musician_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='musician.MusicianProfile'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_comments',
            field=models.ManyToManyField(through='musician.Comment', to='musician.MusicianProfile'),
        ),
        migrations.AddField(
            model_name='hasskill',
            name='endorse_user',
            field=models.ManyToManyField(to='musician.MusicianProfile'),
        ),
        migrations.AddField(
            model_name='hasskill',
            name='musicianprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', to='musician.MusicianProfile'),
        ),
        migrations.AddField(
            model_name='hasskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.Skill'),
        ),
        migrations.AddField(
            model_name='comment',
            name='musician_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.MusicianProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.Post'),
        ),
        migrations.AddField(
            model_name='musicianprofile',
            name='skills',
            field=models.ManyToManyField(through='musician.HasSkill', to='musician.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='hasskill',
            unique_together=set([('musicianprofile', 'skill')]),
        ),
    ]
