# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_auto_20190308_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=50, unique=True)),
                ('comment', models.ManyToManyField(blank=True, to='musician.Comment')),
                ('post', models.ManyToManyField(blank=True, to='musician.Post')),
            ],
        ),
    ]
