# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0004_auto_20190321_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'unrated'), (1, 'Liked'), (2, 'Disliked')], default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('musician_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.MusicianProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.Post')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
