# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0005_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='n_dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='n_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
