# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0008_auto_20190402_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='n_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='n_like',
            field=models.IntegerField(default=0),
        ),
    ]
