# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0010_auto_20190402_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='suggested_friend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),

    ]
