# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0011_musicianprofile_suggested_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
